import React, { useEffect, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { TemporaryPasswordProps } from "./core/model";
import { Switch } from "@/components/ui/switch";
import { Icons } from "@/components/common/icons";

import {
  isPasswordCombinationLetterNumberSymbol,
  isPasswordContainUppercase,
  isPasswordLeast8Char,
} from "../../core/hooks";
import { InputPassword } from "@/components/ui/input-password";
import {
  CreateAccountFormErrors,
  CreateAccountFormTouched,
} from "../../core/model";

const TemporaryPassword: React.FC<TemporaryPasswordProps> = ({ formik }) => {
  const { values, errors, touched, setFieldValue, handleBlur } = formik;
  const temporaryPassword = values.temporaryPassword;
  const temporaryPasswordErrors = (errors as CreateAccountFormErrors)
    .temporaryPassword;
  const temporaryPasswordTouched = (touched as CreateAccountFormTouched)
    .temporaryPassword;

  const [passwordVisible, setPasswordVisible] = useState(false);
  const [rePasswordVisible, setRePasswordVisible] = useState(false);

  useEffect(() => {
    setFieldValue("temporaryPassword.password", "");
  }, [temporaryPassword.passwordField, setFieldValue]);

  useEffect(() => {
    setFieldValue("temporaryPassword.passwordConfirm", "");
  }, [temporaryPassword.passwordField, setFieldValue]);

  const passwordValidateSection = () => {
    return (
      <div className="pt-2">
        <div className="flex w-full items-center self-center">
          <div className="pr-2 ">
            {isPasswordLeast8Char(temporaryPassword.password) ? (
              <Icons.check_circle />
            ) : (
              <Icons.cross_circle />
            )}
          </div>
          <div className="pt-2">
            <p className="pb-2 text-b-14-14-400 text-[var(--color-gray-600)]">
              At least 8 characters
            </p>
          </div>
        </div>
        <div className="flex w-full items-center self-center">
          <div className="pr-2 ">
            {isPasswordContainUppercase(temporaryPassword.password) ? (
              <Icons.check_circle />
            ) : (
              <Icons.cross_circle />
            )}
          </div>
          <div className="pt-2">
            <p className="pb-2 text-b-14-14-400 text-[var(--color-gray-600)]">
              At least one uppercase letter
            </p>
          </div>
        </div>
        <div className="flex w-full items-center self-center">
          <div className="pr-2 ">
            {isPasswordCombinationLetterNumberSymbol(
              temporaryPassword.password
            ) ? (
              <Icons.check_circle />
            ) : (
              <Icons.cross_circle />
            )}
          </div>
          <div className="pt-2">
            <p className="pb-2 text-b-14-14-400 text-[var(--color-gray-600)]">
              A combination of letters, numbers, and symbols
            </p>
          </div>
        </div>
      </div>
    );
  };

  return (
    <Card id="temporary-password">
      <CardHeader>
        <CardTitle>Temporary Password</CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Set Temporary Password - For next phase */}
        {/* <div className="flex items-center gap-4">
          <Label
            htmlFor="passwordField"
            className="w-48 text-left text-sm font-medium"
          >
            Set Temporary Password
          </Label>
          <Switch
            id="passwordField"
            checked={temporaryPassword.passwordField}
            onCheckedChange={(checked) => {
              setFieldValue("temporaryPassword.passwordField", checked);
            }}
          />
        </div> */}

        <div>
          <p className="text-gray-600 text-xs font-normal font-['Inter'] leading-5">
            A temporary password is provided for the user's first login. After
            successfully logging in, the user will be required to change the
            password. If toggle is OFF, temporary password will be randomly
            generated by our system.
          </p>
        </div>

        {/* Password fields - For next phase */}
        {/* {temporaryPassword.passwordField && (
          <>
            <div className="flex items-start gap-4">
              <Label
                htmlFor="password"
                className="w-48 text-left text-sm font-medium"
              >
                Temporary Password
              </Label>
              <div className="flex-1">
                <InputPassword
                  id="password"
                  name="temporaryPassword.password"
                  placeholder="New temporary password"
                  value={temporaryPassword.password}
                  onChange={(e: any) => {
                    setFieldValue("temporaryPassword.password", e.target.value);
                  }}
                  onBlur={handleBlur}
                />
                <div>{passwordValidateSection()}</div>
                {temporaryPasswordTouched?.password &&
                  temporaryPasswordErrors?.password && (
                    <p className="text-sm text-red-500 mt-1">
                      {temporaryPasswordErrors.password}
                    </p>
                  )}
              </div>
            </div>
            <div className="flex items-center gap-4">
              <Label
                htmlFor="ReTempPasswordForm"
                className="w-48 text-left text-sm font-medium"
              >
                Confirm Temporary Password
              </Label>
              <div className="flex-1">
                <InputPassword
                  id="ReTempPasswordFormInput"
                  name="temporaryPassword.passwordConfirm"
                  placeholder="New temporary password"
                  value={temporaryPassword.passwordConfirm}
                  onChange={(e: any) => {
                    setFieldValue(
                      "temporaryPassword.passwordConfirm",
                      e.target.value
                    );
                  }}
                  onBlur={handleBlur}
                />
                {temporaryPasswordTouched?.passwordConfirm &&
                  temporaryPasswordErrors?.passwordConfirm && (
                    <p className="text-sm text-red-500 mt-1">
                      {temporaryPasswordErrors.passwordConfirm}
                    </p>
                  )}
              </div>
            </div>
          </>
        )} */}
      </CardContent>
    </Card>
  );
};

export default TemporaryPassword;
