import React, { useEffect, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { TemporaryPasswordProps } from "./core/types";
import { Switch } from "@/components/ui/switch";
import { Button } from "@/components/ui/button";
import { Circle, Cross, Eye, EyeOff } from "lucide-react";
import { Icons } from "@/components/common/icons";

import {
  isPasswordCombinationLetterNumberSymbol,
  isPasswordContainUppercase,
  isPasswordLeast8Char,
} from "../../core/hooks";
import { InputPassword } from "@/components/ui/input-password";

const TemporaryPassword: React.FC<TemporaryPasswordProps> = ({
  groupValue,
  setValue,
}) => {
  const [passwordVisible, setPasswordVisible] = useState(false);
  const [rePasswordVisible, setRePasswordVisible] = useState(false);

  useEffect(() => {
    setValue("password", "");
  }, [groupValue.passwordField]);
  useEffect(() => {
    setValue("passwordConfirm", "");
  }, [groupValue.passwordField]);

  const passwordValidateSection = () => {
    return (
      <div className="pt-2">
        <div className="flex w-full items-center self-center">
          <div className="pr-2 ">
            {isPasswordLeast8Char(groupValue.password) ? (
              <Icons.check_circle />
            ) : (
              <Icons.cross_circle />
            )}
          </div>
          <div className="pt-2">
            <p className="pb-2 text-b-14-14-400 text-[var(--color-gray-600)]">
              At least 8 characters
            </p>
          </div>
        </div>
        <div className="flex w-full items-center self-center">
          <div className="pr-2 ">
            {isPasswordLeast8Char(groupValue.password) ? (
              <Icons.check_circle />
            ) : (
              <Icons.cross_circle />
            )}
          </div>
          <div className="pt-2">
            <p className="pb-2 text-b-14-14-400 text-[var(--color-gray-600)]">
              At least one uppercase letter
            </p>
          </div>
        </div>
        <div className="flex w-full items-center self-center">
          <div className="pr-2 ">
            {isPasswordCombinationLetterNumberSymbol(groupValue.password) ? (
              <Icons.check_circle />
            ) : (
              <Icons.cross_circle />
            )}
          </div>
          <div className="pt-2">
            <p className="pb-2 text-b-14-14-400 text-[var(--color-gray-600)]">
              A combination of letters, numbers, and symbols
            </p>
          </div>
        </div>
      </div>
    );
  };

  return (
    <Card id="temporary-password">
      <CardHeader>
        <CardTitle>Temporary Password</CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Company Name */}
        <div className="flex items-center gap-4">
          <Label
            htmlFor="setTempPassword"
            className="w-48 text-left text-sm font-medium"
          >
            Set Temporary Password
          </Label>
          <Switch
            id="setTempPassword"
            checked={groupValue.passwordField}
            onCheckedChange={(val: boolean) => {
              setValue("passwordField", val);
            }}
          />
        </div>
        <div>
          <p className="pt-0.5 text-b-12-12-400 text-[var(--color-gray-600)]">
            A temporary password is provided for the user’s first login. After
            successfully logging in, the user will be required to change the
            password. If toggle is OFF, temporary password will be randomly
            generated by our system.
          </p>
        </div>

        {groupValue.passwordField && (
          <>
            <div className="flex items-start gap-4">
              <Label
                htmlFor="password"
                className="w-48 text-left text-sm font-medium"
              >
                Temporary Password
              </Label>
              <div className="flex-1">
                <InputPassword
                  id="password"
                  placeholder="New temporary password"
                  value={groupValue.password}
                  onChange={(e: any) => {
                    setValue("password", e.target.value);
                  }}
                />
                <div>{passwordValidateSection()}</div>
              </div>
            </div>
            <div className="flex items-center gap-4">
              <Label
                htmlFor="ReTempPasswordForm"
                className="w-48 text-left text-sm font-medium"
              >
                Confirm Temporary Password
              </Label>
              <div className="flex-1">
                <InputPassword
                  id="ReTempPasswordFormInput"
                  placeholder="New temporary password"
                  value={groupValue.passwordConfirm}
                  onChange={(e: any) => {
                    setValue("passwordConfirm", e.target.value);
                  }}
                />
              </div>
            </div>
          </>
        )}
      </CardContent>
    </Card>
  );
};

export default TemporaryPassword;
